### ISSUE TITLE
Missing docs for hydra-fractals?

### ISSUE THREAD

**Issue by genbs** [ritchse/hydra-extensions#1]
The url of the documentation for hydra-fractal leads to an existing link 

https://github.com/ritchse/hydra-extensions#hydra-fractals

**Comment by ritchse** [comment]
yh I know, i just left that one for last as documentation isn't as necessary (if you go to the url the names of the functions are kinda self explanatory except for inversion). thx 4 reminding me tho, i could totally document this between today and tomorrow
